- name: Update sshd config to enable challenge responses (PAM - off)
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^ChallengeResponseAuthentication
              line="ChallengeResponseAuthentication no"
              state=present
  notify: restart ssh

- name: Update sshd config to enable challenge responses (PAM - off)
  lineinfile: dest=/etc/ssh/sshd_config
              regexp=^UsePAM
              line="UsePAM no"
              state=present
  notify: restart ssh

- name: Update sshd config to enable challenge responses (PAM - off)
  lineinfile: dest=/etc/pam.d/sshd
              regexp=^pam_google_authenticator.so
              line="#auth    required        pam_google_authenticator.so"
              state=present
  notify: restart ssh
