google_auth_version: 1.0

user_name: user_2fa
admin_email: "{{ user_name }}@{{ domain }}"
user_shell: "/bin/bash"

admin_email: soc@ourdomain.org

# ssh hardening
kex_algorithms: "diffie-hellman-group-exchange-sha256"
ciphers: "aes256-ctr"
macs: "hmac-sha2-512"


#group_name: 2fa 
